CREATE TABLE place
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255),
    PRIMARY KEY (id)
);

INSERT INTO place (name)
VALUES ('Tjentiste');
INSERT INTO place (name)
VALUES ('Trebevic');
INSERT INTO place (name)
VALUES ('Kravice');
