CREATE TABLE photo
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY,
    name     varchar(255),
    path     varchar(255),
    place_id bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE photo
    ADD CONSTRAINT FKsv2aa83c398y2xp3j01yi92rh
        FOREIGN KEY (place_id) REFERENCES place;

INSERT INTO photo (name, path, place_id)
VALUES ('Screenshot 2021-07-18 at 22.42.42.png',
        'src/main/resources/image-storage/2021-07-18T23:24:02.969989-Screenshot 2021-07-18 at 22.42.42.png', 3);
INSERT INTO photo (name, path, place_id)
VALUES ('Screenshot 2021-07-18 at 22.42.00.png',
        'src/main/resources/image-storage/2021-07-18T23:25:41.449378-Screenshot 2021-07-18 at 22.42.00.png', 1);
INSERT INTO photo (name, path, place_id)
VALUES ('Screenshot 2021-07-18 at 22.41.49.png',
        'src/main/resources/image-storage/2021-07-18T23:26:11.521984-Screenshot 2021-07-18 at 22.41.49.png', 1);
