CREATE TABLE users
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY,
    password varchar(255),
    username varchar(255),
    PRIMARY KEY (id)
);

-- password: secretpassword
INSERT INTO users (username, password)
VALUES ('burek', '$2a$10$p6nFCs8ZKPrv7VJzfMzSiOCgU5oxeQhim9gQB6QRrPtLjucBtfaxC');
